### PR TITLE
Fix error of invalid props with react 15.3.0.

### PR DESCRIPTION
**Pull request by marcelopereirascmspain**
This PR solves the warning message with React 15 when passing invalid props to dom elements.

Also it uses the latest version of react-addons-transition-group.

"Warning: Unknown props `delay`, `duration`, `fade`, `initial` on <div> tag. Remove these props from the element."

### CODE REVIEW

**Comment by kenwheeler** [comment]
I would much prefer that we destructure those props out, as opposed to completely removing the ability to expose the HTML api

**Comment by marcelopereirascmspain** [comment]
Ok! Could you review again please?

**Comment by marcelopereirascmspain** [comment]
Ping :)

**Comment by marcelopereirascmspain** [comment]
@kenwheeler done! Could you review again please?

**Comment by marcelopereirascmspain** [comment]
Ping.

**Comment by marcelopereirascmspain** [comment]
@kenwheeler can this project get some love? Thanks in advance.

**Pull request merged**
